spring:
  application:
    name: mybatis-redis
  # 配置运行环境
  profiles:
            active: prod

  # 配置文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      accept_empty_string_as_null_object: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

   # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: bryan
    password: QC456qc!
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      # 初始化连接池大小
      initial-size: 5
      # 连接池最小值
      min-idle: 5
      # 连接池最大值
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall,log4j2
      stat-view-servlet:
        login-username: admin
        login-password: admin
        allow: 0.0.0.0
        enabled: true
      web-stat-filter:
        enabled: true




    # 配置redis
  redis:
    host: 192.168.56.101
    port: 6379
    lettuce:
      pool:
        max-active: 20
        min-idle: 2
        max-idle: 8
        max-wait: 3000
    # 链接超时时间 单位 ms（毫秒）
    timeout: 3000




# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bryan.domain
  configuration:
    #设置自动驼峰转换
    map-underscore-to-camel-case: true


#日志级别
#logging.level.root=info
#所有包下面都以debug级别输出
#logging.level.org.springframework.*=debug
